version: '3.7'

services:
  redis:
    image: redis:latest
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: database
      POSTGRES_USER: username

  itunes_scraper:
    build:
      context: ./
      dockerfile: ./Dockerfile.itunesScraper
    depends_on:
      - redis

  rss_scraper:
    build:
      context: ./
      dockerfile: Dockerfile.rssScraper
    depends_on:
      - redis
  
  downloader:
    build:
      context: ./
      dockerfile: Dockerfile.downloader
    depends_on:
      - redis

  transcriber:
    build:
      context: ./
      dockerfile: Dockerfile.transcriber
    depends_on:
      - redis
      - postgres

