FROM python:3.11
WORKDIR /app

COPY RSSScraper.py /app/RSSScraper.py
COPY Downloader.py /app/Downloader.py
COPY Transcriber.py /app/Transcriber.py

COPY requirements_rss_scraper.txt /app/requirements_rss_scraper.txt 
COPY Episode.py /app/Episode.py


WORKDIR /app

RUN pip install --no-cache-dir -r requirements_rss_scraper.txt

CMD ["python", "RSSScraper.py"]