FROM python:3.11
WORKDIR /app

COPY ItunesScraper.py /app/ItunesScraper.py
COPY RSSScraper.py /app/RSSScraper.py
COPY Downloader.py /app/Downloader.py
COPY Transcriber.py /app/Transcriber.py

COPY Episode.py /app/
COPY genre_links.csv /app/

COPY requirements_itunes_scraper.txt /app/

RUN python3 -m pip install --no-cache-dir -r requirements_itunes_scraper.txt

CMD ["python", "ItunesScraper.py"]
